name: CI/CD for Tomcat

on:
  push:
    branches:
      - DEV
  pull_request:
    branches:
      - DEV

jobs:
  deploy:
    runs-on: self-hosted  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Ansible playbook
      run: |
        ansible-playbook -i inventory.ini Tomcatpb.yml
